// Generated by gencpp from file motor_controller/pfd.msg
// DO NOT EDIT!


#ifndef MOTOR_CONTROLLER_MESSAGE_PFD_H
#define MOTOR_CONTROLLER_MESSAGE_PFD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_controller
{
template <class ContainerAllocator>
struct pfd_
{
  typedef pfd_<ContainerAllocator> Type;

  pfd_()
    : distance(0)
    , angle(0)  {
    }
  pfd_(const ContainerAllocator& _alloc)
    : distance(0)
    , angle(0)  {
  (void)_alloc;
    }



   typedef int8_t _distance_type;
  _distance_type distance;

   typedef int8_t _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::motor_controller::pfd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_controller::pfd_<ContainerAllocator> const> ConstPtr;

}; // struct pfd_

typedef ::motor_controller::pfd_<std::allocator<void> > pfd;

typedef boost::shared_ptr< ::motor_controller::pfd > pfdPtr;
typedef boost::shared_ptr< ::motor_controller::pfd const> pfdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_controller::pfd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_controller::pfd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motor_controller::pfd_<ContainerAllocator1> & lhs, const ::motor_controller::pfd_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motor_controller::pfd_<ContainerAllocator1> & lhs, const ::motor_controller::pfd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motor_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motor_controller::pfd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_controller::pfd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_controller::pfd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_controller::pfd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_controller::pfd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_controller::pfd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_controller::pfd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f2f798034d31200675698594323e8ee";
  }

  static const char* value(const ::motor_controller::pfd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f2f798034d31200ULL;
  static const uint64_t static_value2 = 0x675698594323e8eeULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_controller::pfd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_controller/pfd";
  }

  static const char* value(const ::motor_controller::pfd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_controller::pfd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 distance\n"
"int8 angle\n"
;
  }

  static const char* value(const ::motor_controller::pfd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_controller::pfd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pfd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_controller::pfd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_controller::pfd_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<int8_t>::stream(s, indent + "  ", v.distance);
    s << indent << "angle: ";
    Printer<int8_t>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_CONTROLLER_MESSAGE_PFD_H
