TrajectoryPlannerROS:
  max_vel_x: 0.1
  min_vel_x: 0.02
  max_vel_theta: 0.2
  min_in_place_vel_theta: 0.1

  acc_lim_theta: 0.2
  acc_lim_x: 0.1
  acc_lim_y: 0.5

  holonomic_robot: false

  meter_scoring: true

  yaw_goal_tolerance: 0.4
  xy_goal_tolerance: 0.4
  latch_xy_goal_tolerance: true
